---
  # Required for downloading the package.
  - name: Install Maven
    become: yes
    yum:
      name: maven
      state: present

  # Required for maven_artifact.
  - name: Install PIP
    become: yes
    yum:
      name: python-pip
      state: present

  # Required for maven_artifact.
  - name: Install lxml
    become: yes
    pip:
      name: lxml
      state: present

  - name: Copy init.d service file
    become: yes
    template:
      src: service.j2
      dest: /etc/init.d/open-game-backend-{{ service_name }}
      mode: '0755'

  - name: Copy systemd service file
    become: yes
    template:
      src: app.service
      dest: /etc/systemd/system/open-game-backend-{{ service_name }}.service
      mode: '0755'

  - name: Stop service, if started
    become: yes
    service:
      name: open-game-backend-{{ service_name }}
      state: stopped

  - name: Create application directory if it does not exist
    become: yes
    file:
      path: /usr/local/bin/open-game-backend
      state: directory
      mode: '0755'

  - name: Download package
    become: yes
    community.general.maven_artifact:
      group_id: de.opengamebackend
      artifact_id: "{{ service_name }}"
      version: latest
      repository_url: https://maven.pkg.github.com/open-game-backend/{{ service_name }}
      username: "{{ github_user }}"
      password: "{{ github_token }}"
      dest: /usr/local/bin/open-game-backend/{{ service_name }}.jar
      mode: '0755'
      state: present
      verify_checksum: always

  - name: Copy configuration file
    become: yes
    template:
      src: templates/{{ service_name }}.application.yml
      dest: /usr/local/bin/open-game-backend/{{ service_name }}.application.yml
      mode: '0555'

  - name: Start service immediately and after boot
    become: yes
    service:
      name: open-game-backend-{{ service_name }}
      state: started
      enabled: yes
