spring:
  datasource:
    url: jdbc:mariadb://localhost/open_game_backend
    username: {{ db_user_auth }}
    password: {{ db_pass_auth }}

eureka:
  client:
    serviceUrl:
      defaultZone: {{ registry_url }}
  instance:
    hostname: {{ registry_host }}

de:
  opengamebackend:
    auth:
      provider:
        github:
          redirectUri: {{ admin_url }}/login
          clientId: {{ github_client_id }}
          clientSecret: {{ github_client_secret }}
