spring:
  datasource:
    url: jdbc:mariadb://localhost/open_game_backend
    username: {{ vault_db_user_matchmaking }}
    password: {{ vault_db_pass_matchmaking }}

eureka:
  client:
    serviceUrl:
      defaultZone: {{ registry_url }}
  instance:
    hostname: {{ registry_host }}
