---
- name: Install Open Game Backend Auth
  hosts: auth
  remote_user: "{{ system_user_auth }}"
  vars_files:
    - group_vars/vars
    - group_vars/vault
  roles:
    - role: deploy_mariadb
      vars:
        db_user: "{{ db_user_auth }}"
        db_pass: "{{ db_pass_auth }}"
    - role: deploy_spring_boot_service
      vars:
        service_name: auth
