---
- name: Install Open Game Backend Collection
  hosts: collection
  remote_user: "{{ system_user_collection }}"
  vars_files:
    - group_vars/vars
    - group_vars/vault
  roles:
    - role: deploy_mariadb
      vars:
        db_user: "{{ db_user_collection }}"
        db_pass: "{{ db_pass_collection }}"
    - role: deploy_spring_boot_service
      vars:
        service_name: collection
