---
- name: Install Open Game Backend Matchmaking
  hosts: matchmaking
  remote_user: "{{ system_user_matchmaking }}"
  vars_files:
    - group_vars/vars
    - group_vars/vault
  roles:
    - role: deploy_spring_boot_service
      vars:
        service_name: matchmaking
    - role: deploy_mariadb
      vars:
        vault_db_user: "{{ vault_db_user_matchmaking }}"
        vault_db_pass: "{{ vault_db_pass_matchmaking }}"
